apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-app-configmap
  namespace: bank-app
data:
  db_host: "jdbc:mysql://bank-database-statefulset-service.bank-database.svc.cluster.local:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
