apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp2 # Example for AWS
  encrypted: "true" # Set to "true" if encryption is required
volumeBindingMode: WaitForFirstConsumer
#volumeBindingMode: Immediate
#allowedTopologies:
#  - matchLabelExpressions:
#      - key: topology.kubernetes.io/zone
#        values:
#          - us-east-1a # Example: us-east-1a
