apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-app-frontend-deployment
  annotations:
    kubernetes.io/change-cause: "Updating image to portal-app-frontend:V1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-app-frontend
  template:
    metadata:
      labels:
        app: portal-app-frontend
    spec:
      containers:
        - name: portal-app-frontend
          image: kosaraju333/portal-app-frontend:V1
          #image: nginx:1.20
          env: 
            - name: HOST
              value: "localhost"
            - name: PORT
              value: "5432"
            - name: USER
              value: "postgres"
            - name: PASSWORD
              value: "postgres"
            - name: DATABASE
              value: "spontan"
            - name: listen_PORT
              value: "3000"
          ports:
            - containerPort: 3000
