apiVersion: v1
kind: Service
metadata:
  name: portal-database-headless-service
  namespace: portal-database
spec:
  clusterIP: None # <= Don't forget!!
  selector:
    app: portal-database-statefulset
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
