apiVersion: v1
kind: Service
metadata:
  name: portal-app-frontend-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: portal-app-frontend
  ports:
    # Below Port number is a service port number
    - port: 3000
      # Below targetPort is a Container Port number
      targetPort: 3000
