apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: portal-app-db-aws-secrets
  namespace: portal-database
spec:
  provider: aws
  secretObjects:                          # <== This enables syncing to a Kubernetes Secret
  - secretName: portal-database-secrets            # name of the K8s secret
    type: Opaque
    data:
    - objectName: "portal-app-databse-secrests"     # AWS Secrets Manager key
      key: user
    - objectName: "portal-app-databse-secrests"
      key: password
    - objectName: "portal-app-databse-secrests"
      key: database
  parameters:
    objects: |
      - objectName: "portal-app-databse-secrests"
        objectType: "secretsmanager"
