apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bank-database-statefulset
  namespace: bank-database
  labels:
    app: bank-database-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-database-statefulset
  template:
    metadata:
      name: bank-database-statefulset-app
      labels:
        app: bank-database-statefulset
    spec:
      containers:
      - name: bank-database-statefulset-container
        image: mysql:8
          #imagePullPolicy: "IfNotPresent"
          #image: postgres:latest
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bank-database-secrets
                key: root_password

          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: bank-database-secrets
                key: database_name

        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-db

  volumeClaimTemplates:
  - metadata:
      name: mysql-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "mysql-ebs-sc"
      resources:
        requests:
          storage: 1Gi