apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-app-configmap
  namespace: portal-app
data:
  host: "portal-database-statefulset-service.portal-database.svc.cluster.local"
  port: "5432"
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        server {
            listen       443 ssl;
            server_name portal-app-service.portal-app.svc.cluster.local;

            ssl_certificate /etc/nginx/ssl/tls.crt;  # Path to the certificate
            ssl_certificate_key /etc/nginx/ssl/tls.key;  # Path to the certificate key

            location / {
                proxy_pass http://localhost:3000;  # Adjust to the correct target for your app
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
